apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: liberty-hello-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
        - name: subdirectory
          value: ""
        - name: revision
          value: "main"

    - name: build-and-push
      runAfter: ["fetch-repo"]
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: FORMAT
          value: docker
